---
- name: update univention apps
  shell:
    cmd: "/usr/bin/univention-app update"
  tags: apps

- name: install apps from appstore
  shell:
    cmd: "/usr/bin/univention-app install {{ item }} --username Administrator --noninteractive --pwdfile <({{ rootpassword }})"
  loop:
    - letsencrypt
    - etherpad-lite
    - rocketchat
    - openid-connect-provider
    - owncloud
  tags: apps
